Theano is a Python library for fast numerical computation that can be run on the CPU or GPU (which is accessible with AWS). Theano allows you to define, optimize, and evaluate mathematical expressions (symbolic) including multi-dimensional arrays efficiently. It can be used to create deep learning models.

In [1]:
import theano
from theano import tensor as T, function

import numpy as np

# Function definitions

Theano allows us to create symbolic expressions and manipulate them how we want (even with derivatives and more!).

Here we will define one independent variable and two dependent variables and find out how Theano works.

In [9]:
X = T.matrix('x')
Y = X ** 2 # x^2

Z = T.grad(Y.sum(), X) # deriving dy/dx -> z = d(x^2)/dx = 2*x

F = function([X], [Y, Z]) # compile


In [10]:
x = np.ones((2,2)) * 3
y, z = F(x) # takes our numpy array and inputs in symbolic function

# Print results

In [11]:
print(x)
print('-'*12)
print(y)
print('-'*12)
print(z)

[[ 3.  3.]
 [ 3.  3.]]
------------
[[ 9.  9.]
 [ 9.  9.]]
------------
[[ 6.  6.]
 [ 6.  6.]]


As we can see, Theano easily manipulates the expressions to arrive at the numerical values we are looking for.

We can use Keras which is a wrapper library that hides Theano completely and provides a very simple API to create work with to create  deep learning models.